apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: default
spec:
  project: frontend
  source:
    repoURL: https://github.com/cDevOps80/ArgoCD-Roboshop.git
    path: roboshop-helm
    targetRevision: main
    helm:
      valueFiles:
        - ../dev-values/frontend.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default