apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    component: {{ .Release.Name }}
spec:
  containers:
    - name: {{ .Release.Name }}
      image: docker.io/chaitu1812/{{ .Release.Name }}-rhel9:{  { default "latest" .Values.Image.tag }}
      env:
      {{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: {{ $v | quote }}
      {{- end }}
      imagePullPolicy: Always
      ports:
        - containerPort: {{ .Values.service.containerport }}




