apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ default "latest" .Values.Image.tag | replace "." "-" }}
spec:
  containers:
    - name: {{ .Release.Name }}
      image: {{ .Release.Name }}-rhel9:{{ default "latest" .Values.Image.tag }}
      env:
       {{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: {{ $v }}
       {{- end }}
      imagePullPolicy: Always



