apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ Values.Image.tag }}
spec:
  containers:
    - name: {{ Release.Name }}
      image: {{ default "docker.io" .Values.Image.registry }}/{{ .Release.Name }}:{{ Values.Image.tag | replace "-" "." }}

