apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Values.Image.tag | replace "." "-" }}
spec:
  containers:
    - name: {{ .Release.Name }}
      image: {{ default "docker.io" .Values.Image.registry }}/{{ .Release.Name }}-rhel9:{{ default "latest" .Values.Image.tag }}
      env:
       {{ range $key,$value :- .Values.env }}
         name: {{ $key }}
         value: {{ $value }}
       {{ end }}


