{{- if .Values.load_schema.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name  }}-load-schema
  annotations:
    "helm.sh/hook": pre-install
spec:
  restartPolicy: Never
  containers:
    - name: {{ .Release.Name  }}-load-schema
      image: chaitu1812/load-schema-rhel9
      env:
      {{- range $k, $v := .Values.load_schema.env }}
        - name: {{ $k  }}
          value: {{ $v }}
      {{- end }}
      imagePullPolicy: Always
{{- end }}



